version: '3.8'

services:
  app:
    env_file:
     - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blendsk_app
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./var:/var/www/html/var
    environment:
      APP_ENV: ${APP_ENV:-prod}
      DATABASE_URL: ${DATABASE_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      MAILER_DSN: ${MAILER_DSN}

    depends_on:
      db:
        condition: service_healthy
    networks:
      - ci_cd_network


volumes:
  db_data:
  jenkins_home:
  sonarqube_db_data:

networks:
  ci_cd_network:
