version: '3.8'

services:
  app:
    build: .
    container_name: blendsk_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      # Veillez à ce que cette variable corresponde à votre configuration Symfony (.env)
      DATABASE_URL: "mysql://root:root@db:3306/blendsk"

  db:
    image: mysql:8.0
    container_name: blendsk_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blendsk
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
